-- 1. CADASTRO MESTRE DO PRODUTO
CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    part_number TEXT UNIQUE NOT NULL,
    descricao TEXT NOT NULL
);

-- 2. ENGENHARIA DE PROCESSOS E ROTEIROS
CREATE TABLE IF NOT EXISTS processos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    nome_operacao TEXT NOT NULL,
    tempo_segundos INTEGER NOT NULL,
    custo_mod REAL NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);

-- 3. MATERIAIS, MAQUINAS E INSUMOS
CREATE TABLE IF NOT EXISTS materiais (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    nome_material TEXT NOT NULL,
    preco_unitario REAL NOT NULL,
    fonte_url TEXT,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);
