-- 1. CADASTRO MESTRE DO PRODUTO
CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    part_number TEXT UNIQUE NOT NULL,
    descricao TEXT NOT NULL
);

-- 2. ENGENHARIA DE PROCESSOS E ROTEIROS
CREATE TABLE IF NOT EXISTS processos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    nome_operacao TEXT NOT NULL,
    tempo_segundos INTEGER NOT NULL,
    custo_mod REAL NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);

-- 3. MATERIAIS, MAQUINAS E INSUMOS
CREATE TABLE IF NOT EXISTS materiais (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    nome_material TEXT NOT NULL,
    preco_unitario REAL NOT NULL,
    fonte_url TEXT,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);



-- 4. TABELA DE PRECIFICACAO E MARK-UP
CREATE TABLE IF NOT EXISTS precificacao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER UNIQUE NOT NULL,
    margem_lucro REAL NOT NULL,
    impostos REAL NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);

-- 5. TABELA DE METAS DE VENDAS
CREATE TABLE IF NOT EXISTS vendas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER NOT NULL,
    quantidade_meta INTEGER NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE
);
